FROM node:22-slim

RUN apt update \
    && apt install --assume-yes --no-install-recommends \
        build-essential \
        python3

WORKDIR /apps/crud-dapp

# ==================================================
# NPM
# ==================================================
COPY package*.json ./
RUN npm ci

COPY . .
CMD [ "npm", "run", "dev" ]